### ISSUE TITLE
Typescript Language Server Erroring because of `escapedName`

### ISSUE THREAD

**Issue by bnussman** [0no-co/GraphQLSP#187]
I've been trying to intergrate this package (with `gql.tada`) into my project (https://github.com/bnussman/beep/pull/77), but the output of `tsc` shows error that do not show up in my editor. I am seeing a tsserver error that might be related. 

I wish I could provide more info, but I'm not sure exactly what steps to take to debug this.

```sh
Info 1369 [19:53:51.363] event:
    {"seq":0,"type":"event","event":"projectsUpdatedInBackground","body":{"openFiles":["/home/banks/Development/beep/app/routes/ride/PickBeep.tsx","/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js"]}}
Info 1370 [19:53:51.566] request:
    {
      "seq": 184,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          "/home/banks/Development/beep/app/routes/ride/PickBeep.tsx",
          "/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js"
        ]
      }
    }
Perf 1371 [19:53:51.566] 184::geterr: async elapsed time (in milliseconds) 0.3520
Info 1372 [19:53:51.568] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/home/banks/Development/beep/app/routes/ride/PickBeep.tsx","diagnostics":[]}}
Err 1373  [19:53:51.579] Exception on executing command delayed processing of request 184:

    Cannot read properties of undefined (reading 'escapedName')

    TypeError: Cannot read properties of undefined (reading 'escapedName')
        at getTypeForVariableLikeDeclaration (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:56154:39)
        at getTypeOfNode (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:85826:14)
        at getSymbolAtLocation (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:85668:31)
        at Object.getSymbolAtLocation (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:47880:21)
        at getReferencesAtLocation (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:163493:41)
        at getReferencesInContainer (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:163477:7)
        at getReferencesInSourceFile (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:163470:12)
        at searchForName (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:163278:7)
        at getReferencesInContainerOrFiles (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:163071:9)
        at getReferencedSymbolsForSymbol (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:163053:7)
        at Object.getReferencedSymbolsForNode (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:162800:24)
        at Object.findReferenceOrRenameEntries (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:162441:34)
        at getReferencesWorker2 (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:144237:41)
        at Object.getReferencesAtPosition (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:144232:12)
        at crawlScope (/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13484:29)
        at _loop (/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13470:15)
        at traverseDestructuring (/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13475:5)
        at /home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13645:17
        at Array.forEach (<anonymous>)
        at /home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13625:7
        at Array.forEach (<anonymous>)
        at checkFieldUsageInFile (/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13573:5)
        at runDiagnostics (/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13978:13)
        at getGraphQLDiagnostics (/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:13824:9)
        at o.getSemanticDiagnostics (/home/banks/Development/beep/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:14099:13)
        at IpcIOSession.semanticCheck (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:183095:125)
        at /home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:183156:14
        at MultistepOperation.executeAction (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:181817:9)
        at /home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:181797:69
        at IpcIOSession.executeWithRequestId (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:184830:14)
        at Object.executeWithRequestId (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:182840:57)
        at Immediate._onImmediate (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:181797:26)
        at process.processImmediate (node:internal/timers:478:21)
Info 1374 [19:53:51.579] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":184}}

```

**Comment by JoviDeCroock** [comment]
It looks like in `PickBeep.tsx` we have an uncovered case for going from `Destructuring` to `ScopeCrawling`, this is most likely us passing in the wrong `start` of a node or TypeScript being confused about the start of a node.

I would have to look deeper into this but for now you can skip the field-usage stuff by disabling it with `trackFieldUsage: "false"`.

**Comment by JoviDeCroock** [comment]
This will get fixed in TypeScript, it basically intersects with a data JSDoc in that bottom sheet library. A workaround could be to rename data to something else like data: queryDats but that feels convoluted. It doesn't look like we can workaround this 😅 I added a try catch for now but the real fix will be in a new TS version

**Comment by bnussman** [comment]
I bumped by version to `"gql.tada": "^1.0.3"` and `"@0no-co/graphqlsp": "^1.0.7"` and everything is working great for me now! 

You rock! 🪨
