### ISSUE TITLE
lack of .mjs breaks deno support (Non-issue as deno TS plugins aren't a thing)

### ISSUE THREAD

**Issue by Jackbennett** [0no-co/GraphQLSP#249]
none-issue because the LSP isn't loaded by deno, see: https://docs.deno.com/runtime/manual/advanced/typescript/faqs#why-dont-you-support-language-service-plugins-or-transformer-plugins

However, I'd already fixed the crash so thought I'd mention it in-case it comes up elsewhere;

```
failed to load config from C:\src\project\vite.config.mts
error when starting dev server:
TypeError: 'import', and 'export' cannot be used outside of module code at file:///C:/src/project/node_modules/.deno/@0no-co+graphqlsp@1.4.1/node_modules/@0no-co/graphqlsp/dist/graphqlsp.module.js:1:1

  import e from "node-fetch";
  ~~~~~~
    at async loadConfigFromBundledFile (file:///C:/src/project/node_modules/.deno/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68383:21)
    at async loadConfigFromFile (file:///C:/src/project/node_modules/.deno/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68240:28)
    at async resolveConfig (file:///C:/src/project/node_modules/.deno/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:67841:28)
    at async _createServer (file:///C:/src/project/node_modules/.deno/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:60327:20)
    at async CAC.<anonymous> (file:///C:/src/project/node_modules/.deno/vite@5.0.12/node_modules/vite/dist/node/cli.js:764:24)
```

To fix this `graphqlsp.module.js` needs to be `graphqlsp.module.mjs` i.e. the .mjs extension instead. Simply renaming that file and the imports mapped in package.json does allow deno to run without error.

But yeh, I see graphql TS types, without the lsp it doesn't make the response types by fetching the schema, but that's denos problem.

**Comment by kitten** [comment]
This looks pretty accidental to me and like an easy fix. TypeScript's built-in plugin loader simply doesn't use their own "async loaders" (which would default to async-import and hence load the ESM version) but to the sync variant, which defaults to using `require`

It's possible that in some instances of Deno's host it passes async-import to load plugins instead.

**Comment by Jackbennett** [comment]
I was curious since Deno 2 and wend digging. The last reference I found to my linked faq was https://deno.land/x/manual@v1.26.2/typescript/faqs.md?source

1.27 improved editor lsp support: https://deno.com/blog/v1.27#language-serveride-improvements

The docs removed reference to plugins here but I can't fend mention for any reason this should now work.
https://github.com/denoland/docs/commit/7809783a478ca4bfcb4ac08a210e90df71edd2a6#diff-22a746d5e7ac9368870b544c0b38a1310602deedb93687ae881000c7b369855c
