### ISSUE TITLE
Intellij fails to report errors from Typescript language service when using gql.tada

### ISSUE THREAD

**Issue by mattias800** [0no-co/GraphQLSP#270]
I have posted this issue in Jetbrains issue tracker as well.

IntelliJ fails to report Typescript errors for some source files when adding the gql.tada Typescript language plugin.

This started happening when we added gql.tada to the project.

For some .tsx files (not all), IntelliJ is not reporting any type errors when gql.tada is enabled.
This occurs 100% of the time for these source files, but most work properly.

I have a normal sized vite project, with normal sized GraphQL schema.

vite typecheck plugin reports the error:

```
 ERROR(TypeScript)  Property 'validation' does not exist on type '{ [$tada.fragmentRefs]: { SearchFilterSearchFilterDraft: "Undefined Fragment"; }; id: string; }'.
 FILE  /Users/mattias800/repos/Booking/WebClient/src/features/start-page/components/StartFetcher.tsx:42:61

    40 |     >
    41 |       <SearchFilterDraftValidationContext.Provider
  > 42 |         value={data.viewer.bookingSession.searchFilterDraft.validation}
       |                                                             ^^^^^^^^^^
    43 |       >
    44 |         <BookingStepsAvailabilityContextProvider value={data}>
    45 |           <StartPanel />
```

And so does `tsc`

```
src/features/start-page/components/StartFetcher.tsx:42:61 - error TS2339: Property 'validation' does not exist on type '{ [$tada.fragmentRefs]: { SearchFilterSearchFilterDraft: "Undefined Fragment"; }; id: string; }'.

42         value={data.viewer.bookingSession.searchFilterDraft.validation}
```

And it works with VSCode.

![image](https://github.com/0no-co/GraphQLSP/assets/1266041/8e8be61e-ecd1-4019-b6fc-049ce425781f)

But IntelliJ does not report this error.

![image](https://github.com/0no-co/GraphQLSP/assets/1266041/ea3d3b17-32d7-490c-878a-e48e774eb36e)

I have added trace logging for the Typescript language service, and I get this log:

```
Err 1074  [10:42:37.269] Exception on executing command {"sessionId":1710927749555,"seq":23,"type":"request","command":"semanticDiagnosticsSync","arguments":{"file":"/Users/mattias800/repos/Booking/WebClient/src/features/start-page/components/StartFetcher.tsx"}}:

    Cannot read properties of undefined (reading 'fileName')

    TypeError: Cannot read properties of undefined (reading 'fileName')
        at unrollFragment (/Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11884:26)
        at /Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11902:21
        at Array.forEach (<anonymous>)
        at unrollFragment (/Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11900:18)
        at /Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11902:21
        at Array.forEach (<anonymous>)
        at unrollFragment (/Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11900:18)
        at /Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11932:23
        at Array.forEach (<anonymous>)
        at find (/Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11930:20)
        at visitNode2 (/Users/mattias800/repos/Booking/WebClient/node_modules/typescript/lib/tsserver.js:30459:18)
        at forEachChildInVariableDeclaration (/Users/mattias800/repos/Booking/WebClient/node_modules/typescript/lib/tsserver.js:30521:123)
        at Object.forEachChild (/Users/mattias800/repos/Booking/WebClient/node_modules/typescript/lib/tsserver.js:30976:35)
        at find (/Users/mattias800/repos/Booking/WebClient/node_modules/@0no-co/graphqlsp/dist/graphqlsp.js:11949:9)
        at visitNodes (/Users/mattias800/repos/Booking/WebClient/node_modules/typescript/lib/tsserver.js:30467:22)
```

The exception occurs here:

https://github.com/0no-co/GraphQLSP/blob/8c79c98ba56c1b86ba28fc05f996640899c07a5a/packages/graphqlsp/src/ast/index.ts#L65

```
  const definitions = info.languageService.getDefinitionAtPosition(
    element.getSourceFile().fileName,
    element.getStart()
  );

  if (!definitions) return fragments;
  const [fragment] = definitions;

  const externalSource = getSource(info, fragment.fileName);
```

`definitions` is an empty list, so `fragment` becomes undefined. And then `fragment.fileName` throws null pointer exception.

I'm trying to verify if empty list is an expected behaviour that graphqlsp doesn't handle, or if it is caused by something. But at this point I need help :)

**Comment by JoviDeCroock** [comment]
Good point, that being said this exception should not cause the IDE to not typecheck 😅 I'll push a fix to the LSP, generally we've seen some weirdness with JetBrains editors as they seem to have their own `tsserver` version
